[package]
    authors = ["Riven Skaye <riven@tae.moe>"]
    edition = "2021"
    license = "MIT OR Apache-2.0"
    name    = "winmmf"
    version = "0.1.0"

[dependencies]
    fixedstr = {version = "0.5.5", features = ["std"]}
    microseh = "1.0"
    windows = {version = "0.54", features = [
        "Win32_Foundation",
        "Win32_Security",
        "Win32_Storage",
        "Win32_Storage_FileSystem",
        "Win32_System_Memory"
    ]}
    windows-ext = "0.0.2"

[features]
    default    = ["impl_lock", "impl_mmf"]
    impl_lock  = []
    impl_mmf   = ["namespaces"]
    namespaces = []
