name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-formatting:
    name: rustfmt checking ${{matrix.package}}
    runs-on: windows-latest
    strategy:
      matrix:
        package:
          - winmmf
          - winmmf-ffi
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - name: rustfmt
        run: cargo fmt --check

  clippy:
    name: Clippy  ${{matrix.package}}
    runs-on: windows-latest
    strategy:
      matrix:
        package:
          - winmmf
          - winmmf-ffi
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy
      - name: clippy
        run: cargo clippy
